<div class="vqa-answer-list">
    <a class="headwapper" href="/user/visit/<?php echo $_p['uid']; ?>">
        <img src="<?php echo $_p['ush']; ?>" width="45px" height="45px"/>
    </a>
    <div class="vqa-answer-list-right">
        <div class="vqa-answer-usn"><?php echo urldecode($_p['usn']); ?> <span>>></span></div>
        <div class="vqa-answer-ct">
            <?php echo $_p['content']; ?>
        </div>
    </div>
    <div class="clear"></div>
</div>