<div class="vqa-more-qs">
    <a class="headwapper" href="/user/visit/<?php echo $Qa_moreList->uid; ?>">
        <img src="<?php echo $Qa_moreList->ush ?>" height="32px" width="32px"/>
    </a>
    <div class="vqa-more-right">
        <a class="autowarp" href="<?php echo Qa_G::getQa_href($Qa_moreList->id); ?>"><?php echo $Qa_moreList->title ?></a>
        <span class="block Gray"><?php echo $Qa_moreList->ansi ?>回/<?php echo $Qa_moreList->readi ?>阅</span>
    </div>
</div>