<div style="margin:10px;height:43px;">
    <a href="/user/<?php echo $params['uid'] ?>" 
       style="display:block;padding:2px;background:#FFF;border:1px solid #CCC;float:left;margin-right:10px">
        <img src="<?php echo $params['headimg'] ?>" width="32px" height="32px" style="display:block;" />
    </a>
    <a class="a-red" style="display:block;margin-bottom:5px;" href="/user/<?php echo $params['uid'] ?>"><?php echo $params['usn'] ?></a>
    <a class="block Elipsis" href="<?php echo $params['href'] ?>"><?php echo $params['title'] ?></a>
    <span class="clear"></span>
</div>