<div style="border-bottom:1px dashed #ccc;margin:2px 10px;padding:5px 0;">
    <a class="headwapper">
        <img src="<?php echo $params['ush']?>" width="32px" height="32px"/>
    </a>
    <span style="line-height:20px;display:block;margin-left:45px;font-size:14px;">
        <a href="/user/ucApp/coder_sale/?uid=<?php echo $params['uid']?>"><?php echo $params['usn']?></a> 
        <span class="block">被我<?php echo $params['ct']?>&nbsp;<span class="Gray"><?php echo $params['time'];?></span></span>
    </span>
    <span class="clear"></span>
</div>