<div style="margin:5px;border-bottom:1px dashed #ccc;">
    <a class="headwapper" style="margin:5px;">
        <img src="<?php echo $params['ush']?>" width="32px" height="32px"/>
    </a>
    <div style="margin-left:32px;line-height:24px;font-size:13px;">
        <a class="block" style="font-size:14px;" href="/user/ucApp/coder_sale/?uid=<?php echo $params['uid'];?>" target="_blank"><?php echo $params['usn']?></a>
        <span class="block"><span class="Gray">目前身价</span>：<?php echo $params['pos']?></span>
    </div>
</div>