<div style="border-bottom:1px dotted #aaa;padding-bottom:15px;margin-left:20px;">
    <h1 style="display:block;text-align:left;">
        <a href="<?php echo $param['url']?>" target="_blank"><?php echo $param['title']?></a>
        <span class="Gray" style="font-weight:normal;font-size:13px;">by <?php echo $param['author']?></span>
    </h1>
    <div class="borderR5" style="background-color:#fff;padding:5px;border:1px solid #ccc;position:relative;margin-top:10px;">
        <tx></tx><t></t>
        <?php echo $param['contentx']?>
    </div>
</div>