<div style="float:left;width:150px;border:1px solid #ccc;padding:5px;background:#fff;margin-right:6px;margin-top:5px;">
    <em class="headwapper">
        <img src="<?php echo $param['ush'];?>" width="45px" height="45px"/>
    </em>
    <div style="margin-left:55px;width:90px;">
        <a class="Elipsis block" href="/user/visit/<?php echo $param['uid'];?>"><?php echo $param['usn'];?></a>
        <span class="block">坚持了 <b><?php echo $param['rec'];?></b> 秒</span>
    </div>
</div>