<div style="margin:15px;margin-top:0;border-bottom:1px dashed #ccc;padding-bottom:5px;*height:50px;">
    <em class="headwapper">
        <img src="<?php echo $param['ush']?>" width="45px" height="45px"/>
    </em>
    <div style="line-height:25px;font-size:14px;margin-left:55px;">
        <a href="/user/<?php echo $param['uid']?>" target="_blank"><?php echo $param['usn']?></a>
        <span class="block">坚持了 <b><?php echo $param['rec']?></b> 秒</span>
    </div>
</div>